name: Linux Container CICD Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        docker login -u "${{ secrets.REGISTRY_USERNAME }}" -p "${{ secrets.REGISTRY_PASSWORD }}" docker.io
        docker build -t patrickdeg/patrickdockerli .
        docker push docker.io/patrickdeg/patrickdockerli:latest    
